# Site settings
title: Sanctum
author: David Joaquín Shourabi Porcel
baseurl: ''
url: https://blog.www.djsp.eu/
email:
    author: david@djsp.eu
    comments: david@djsp.eu
    site: david@djsp.eu
launchdate: 2018-02-05

# Build settings
strict_front_matter: true
excerpt_separator: <!--more-->
compress_html:
    clippings: all
    comments: all
markdown: kramdown
kramdown:
    input: Markdown
sass:
    style: compressed
plugins:
  - jekyll-sitemap

permalink: /:categories/:title

defaults:
    -
        scope:
            path: "es"
        values:
            lang: "es"
    -
        scope:
            path: "en"
        values:
            lang: "en"
    -
        scope:
            path: "de"
        values:
            lang: "de"
    -
        scope:
            path: "es/*/index.html"
        values:
            layout: "category"
    -
        scope:
            path: "en/*/index.html"
        values:
            layout: "category"
    -
        scope:
            path: "de/*/index.html"
        values:
            layout: "category"
    -
        scope:
            path: "tags"
        values:
            layout: "tag"
    -
        scope:
            path: "tags/es"
        values:
            lang: "es"
    -
        scope:
            path: "tags/en"
        values:
            lang: "en"
    -
        scope:
            path: "tags/de"
        values:
            lang: "de"

exclude:
    - TODO.md
    - cfn
    - webline
