---


AWSTemplateFormatVersion: 2010-09-09


Description: 'Blog: hosting.'


Resources:

   Bucket:
      Type: AWS::S3::Bucket
      Properties: {
      }

   OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
         CloudFrontOriginAccessIdentityConfig:
            Comment: S3

   BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
         Bucket:
            Ref: Bucket
         PolicyDocument:
            Version: 2012-10-17
            Statement:
               -
                  Sid: CloudFront
                  Principal:
                     AWS:
                        -
                           Fn::Sub: arn:${AWS::Partition}:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}
                  Action:
                     - s3:GetObject
                  Resource:
                     -
                        Fn::Sub: ${Bucket.Arn}/*
                  Effect: Allow


Outputs:

   BucketName:
      Description: Name of the S3 bucket.
      Value:
         Ref: Bucket

   BucketDomainName:
      Description: Domain name of the S3 bucket.
      Value:
         Fn::GetAtt:
            - Bucket
            - DomainName

   OriginAccessIdentity:
      Description: ID of the CloudFront origin access identity that is allowed to access the bucket.
      Value:
         Ref: OriginAccessIdentity
