---


AWSTemplateFormatVersion: 2010-09-09


Description: 'Blog: distribution.'


Resources:

   Role:
      Type: AWS::IAM::Role
      Properties:
         AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
               -
                  Principal:
                     Service:
                        - lambda.amazonaws.com
                        - edgelambda.amazonaws.com
                  Action:
                     - sts:AssumeRole
                  Effect: Allow
         ManagedPolicyArns:
            -
               'Fn::Sub': 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

   Function:
      Type: AWS::Lambda::Function
      Properties:
         Code:
            ZipFile: |
               table = {
                  'de': 'de',
                  'en': 'en',
                  'es': 'es',
               }

               default_language = 'en'

               def handler(event, context):
                  input_request = event['Records'][0]['cf']['request']
                  headers = input_request['headers']

                  language = default_language

                  try:
                     accept_language = headers['accept-language']
                  except KeyError:
                     pass
                  else:
                     accept_language_value = accept_language[0]['value']
                     first_two = accept_language_value[0:2]
                     try:
                        language = table[first_two]
                     except KeyError:
                        pass

                  uri = f'/{ language }/home'

                  output_request = {
                     'status': '302',
                     'statusDescription': 'Found',
                     'headers': {
                        'location': [
                           {
                              'key': 'Location',
                              'value': uri,
                           },
                        ],
                     },
                  }

                  return output_request
         Handler: index.handler
         Role:
            Fn::GetAtt:
               - Role
               - Arn
         Runtime: python3.7
         Timeout: 5


Outputs:

   FunctionName:
      Description: Name of the Lambda function.
      Value:
         Ref: Function
